---
- hosts: all
  remote_user: root
  #remote_user: root
  #become: yes
  #become_method: sudo

  tasks:
#- name: upgrade all packages
    #yum:
      #name: '*'
      #state: present
  - name: Create group for docker
    group:
      name: docker
      state: absent

  - name: add user called user with sudo right
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes

  - name: set authorized keys from github to user
    authorized_key:
      user: user
      state: present
      key: https://github.com/habbis.keys

   #- name: set authorized keys from github to virt
     #authorized_key:
       #user: virt
       #state: present
       #keys: https://github.com/habbis.keys

  - name: Install packages centos7 and RHEL7
    yum:
      name:
        - cockpit
        - curl
        - wget
        - python2
        - python3
        - python3-pip
        - git
        - vim
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - epel-release
      state: present

  - name: enable cockpit systemd service
    firewalld:
      service: cockpit
      permanent: yes
      state: enabled
